[.c20.arealidea.ru] # ключом является имя файла
inuse-host = "*.c20.arealidea.ru"
inuse-brief = "Все хосты на c20"
inuse-httpTarget = ''
inuse-httpForceHttps = true
inuse-httpsTarget = "192.168.1.111"
inuse-enableLetsencrypt = true
inuse-enableWebsockets = true
inuse-_mtime = 2019-08-29T20:44:25.192031Z
latest-status = []
latest-mtime = 2019-08-29T20:44:25.192031Z

